apiVersion: v1
kind: Service
metadata:
  name: currency-service
  labels:
    app: currency-service
spec:
  type: NodePort
  selector:
    app: currency-service
  ports:
    - port: 80
      targetPort: 80
